### ISSUE TITLE
Posts are shown as "Draft" even after being published

### ISSUE THREAD

**Issue by tailsu** [tinypressco/tinypress-v2#1]
I published a few posts through TinyPress, the posts are shown all good at my GH page, but the "Posts" view at tinypress.co shows that some of my posts are in "Draft" status and when I click "Edit" on them, the posts are completely empty.

There are no JavaScript or Network errors in the browser, so I'm not sure what other information to provide.

**Comment by dainmiller** [comment]
Thanks for reporting this here, Im looking into it!

**Comment by dainmiller** [comment]
Moving to v1 repo.
